/**********************************************************************************************************************
 * \file main.c
 * \copyright Copyright (C) Infineon Technologies AG 2024
 *
 * Use of this file is subject to the terms of use agreed between (i) you or the company in which ordinary course of
 * business you are acting and (ii) Infineon Technologies AG or its licensees. If and as long as no such terms of use
 * are agreed, use of this file is subject to following:
 *
 * Boost Software License - Version 1.0 - August 17th, 2003
 *
 * Permission is hereby granted, free of charge, to any person or organization obtaining a copy of the software and
 * accompanying documentation covered by this license (the "Software") to use, reproduce, display, distribute, execute,
 * and transmit the Software, and to prepare derivative works of the Software, and to permit third-parties to whom the
 * Software is furnished to do so, all subject to the following:
 *
 * The copyright notices in the Software and this entire statement, including the above license grant, this restriction
 * and the following disclaimer, must be included in all copies of the Software, in whole or in part, and all
 * derivative works of the Software, unless such copies or derivative works are solely in the form of
 * machine-executable object code generated by a source language processor.
 *
 * THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE
 * WARRANTIES OF MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE, TITLE AND NON-INFRINGEMENT. IN NO EVENT SHALL THE
 * COPYRIGHT HOLDERS OR ANYONE DISTRIBUTING THE SOFTWARE BE LIABLE FOR ANY DAMAGES OR OTHER LIABILITY, WHETHER IN
 * CONTRACT, TORT OR OTHERWISE, ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS
 * IN THE SOFTWARE.
 *********************************************************************************************************************/
/*********************************************************************************************************************/
/*-----------------------------------------------------Includes------------------------------------------------------*/
/*********************************************************************************************************************/
#include "cy_pdl.h"
#include "cybsp.h"
#include "cy_prot.h"
#include "cy_sysfault.h"
#include "cy_retarget_io.h"
#include "shared.h"

/*********************************************************************************************************************/
/*------------------------------------------------------Macros-------------------------------------------------------*/
/*********************************************************************************************************************/
/* Fault number for CM7_1 Peripheral Master Interface PPU violation */
#if defined(COMPONENT_CAT1C8M)
#define PERI_MS_VIO_2   30
#endif
#if defined(COMPONENT_TVIIC2D6M)
#define PERI_MS_VIO_2   28
#endif
/*********************************************************************************************************************/
/*-------------------------------------------------Global variables--------------------------------------------------*/
/*********************************************************************************************************************/
/*
 * Configuration structure for Fixed Group (GR) PPU
 * Privileged: Read/write, User: Read/write, SECURE: Nonsecure
 */
const cy_stc_ppu_gr_cfg_t  PPU_FIXED_ATTR_ALL_ENABLE =
{
    .userPermission = CY_PROT_PERM_RW,
    .privPermission = CY_PROT_PERM_RW,
    .secure         = 0,
};

/*
 * Configuration structure for Fixed Group (GR) PPU
 * Privileged: No access, User: No access, SECURE: Nonsecure
 */
const cy_stc_ppu_gr_cfg_t  PPU_FIXED_ATTR_ALL_DISABLE =
{
    .userPermission = CY_PROT_PERM_DISABLED,
    .privPermission = CY_PROT_PERM_DISABLED,
    .secure         = 0,
};

/*********************************************************************************************************************/
/*------------------------------------------------Function Prototypes------------------------------------------------*/
/*********************************************************************************************************************/

/*********************************************************************************************************************/
/*---------------------------------------------Function Implementations----------------------------------------------*/
/*********************************************************************************************************************/
/**********************************************************************************************************************
 * Function Name: main
 * Summary:
 *  This is the main function.
 * Parameters:
 *  none
 * Return:
 *  int
 **********************************************************************************************************************
 */
int main(void)
{
    /* Variable for storing character read from terminal */
    uint8_t uartReadValue;

    /* pending fault detection variable */
    uint32_t pendingFault;

    /* halt variable for code example functioning*/
    bool exceptionHalt = false;

    /* Initialize the device and board peripherals */
    if (cybsp_init() != CY_RSLT_SUCCESS)
    {
        CY_ASSERT(0);
    }

    /* enable interrupts */
    __enable_irq();

    /* Initialize retarget-io to use the debug UART port */
    Cy_SCB_UART_Init(UART_HW, &UART_config, NULL);
    Cy_SCB_UART_Enable(UART_HW);
    cy_retarget_io_init(UART_HW);

    /* Initialize shared variable */
    g_shared[0] = IDLE;
    g_shared[1] = IDLE;

    /* set protection for the peripheral GPIO_PRT0_PRT(352) */
    if (Cy_Prot_ConfigPpuFixedSlaveAtt(PERI_MS_PPU_FX_GPIO_PRT0_PRT, (uint16_t)CY_PROT_PCMASK5,
            PPU_FIXED_ATTR_ALL_DISABLE.userPermission, PPU_FIXED_ATTR_ALL_DISABLE.privPermission,
            PPU_FIXED_ATTR_ALL_DISABLE.secure) != CY_RSLT_SUCCESS)
    {
        CY_ASSERT(0);
    }
    if (Cy_Prot_ConfigPpuFixedSlaveAtt(PERI_MS_PPU_FX_GPIO_PRT0_PRT, (uint16_t)CY_PROT_PCMASK6,
            PPU_FIXED_ATTR_ALL_ENABLE.userPermission, PPU_FIXED_ATTR_ALL_ENABLE.privPermission,
            PPU_FIXED_ATTR_ALL_ENABLE.secure) != CY_RSLT_SUCCESS)
    {
        CY_ASSERT(0);
    }

    /* set protection context for CM7_0/1 */
    if (Cy_Prot_SetActivePC(CPUSS_MS_ID_CM7_0, CY_PROT_PC6) != CY_PROT_SUCCESS)
    {
        CY_ASSERT(0);
    }
    if (Cy_Prot_SetActivePC(CPUSS_MS_ID_CM7_1, CY_PROT_PC5) != CY_PROT_SUCCESS)
    {
        CY_ASSERT(0);
    }

    /* Enable CM7_0/1. CY_CORTEX_M7_APPL_ADDR is calculated in linker script, check it in case of problems. */
    Cy_SysEnableCM7(CORE_CM7_0, CY_CORTEX_M7_0_APPL_ADDR);
    Cy_SysEnableCM7(CORE_CM7_1, CY_CORTEX_M7_1_APPL_ADDR);

    /* \x1b[2J\x1b[;H - ANSI ESC sequence for clear screen */
    printf("\x1b[2J\x1b[;H");

    printf("****************** "
           "Memory protection using the PPU "
           "****************** \r\n\n");
    printf("1: Read by CM7_0, 2: Read by CM7_1\r\n");

    for(;;)
    {
        /* Check if the CM0 core requested an CM7 core to read */
        if (g_shared[0] == IDLE)
        {
            /* Check if '1' key or '2' key was pressed */
            uartReadValue = Cy_SCB_UART_Get(UART_HW);
            if (uartReadValue == '1')
            {
                /* Ask CM7_0 to read access GPIO_ENH Port #0 */
                printf("Read access from CM7_0 requested\r\n");
                g_shared[0] = FROM_CM0_CM7_0_READ_GPIO_ENH_0;

            }
            if (uartReadValue == '2')
            {
                /* Ask CM7_1 to read access GPIO_ENH Port #0 */
                printf("Read access from CM7_1 requested\r\n");
                g_shared[0] = FROM_CM0_CM7_1_READ_GPIO_ENH_0;
            }
        }

        /* Check if we received an answer from one of the CM7 cores */
        if (g_shared[0] == FROM_CM7_PENDING_ANSWER)
        {
            printf("answer from CM7 core is: %lu\r\n", g_shared[1]);
            g_shared[0] = IDLE;
            g_shared[1] = IDLE;
        }

        /* Check if we ran into an exception by access violation of the CM7_1 cores */
        if (!exceptionHalt)
        {
            pendingFault = Cy_SysFault_GetPendingFault(FAULT_STRUCT0, CY_SYSFAULT_SET0);
            if (pendingFault & (1 << PERI_MS_VIO_2))
            {
                printf("CM7_1 Peripheral Master Interface PPU violation.\r\n");
                printf("A reset is required to recover from that exception\r\n");
                exceptionHalt = true;
            }
        }
        Cy_SysLib_Delay(SLEEP_TIME_MS);
    }
}

/* [] END OF FILE */
